name: Manual Alpha Build and Publish Multi-Arch Docker Images

on:
  workflow_dispatch: # Ручной запуск
env:
  VERSION: "Alpha"
jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Для GHCR
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Для gh api
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Замени на ${{ secrets.PACKAGE_TOKEN }} для PAT
      PACKAGE_OWNER: medium1992
      PACKAGE_NAME: mihomo-proxy-ros # Имя пакета с / для action
      PACKAGE_NAME_ENCODED: mihomo-proxy-ros # Экранированное имя для API
      DELETE_UNTAGGED: "true" # "true" для удаления, "false" для dry-run

    steps:
      # 1. Установка jq для парсинга JSON и crane
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # 2. Получаем текущий репозиторий
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
    
      # 3. Устанавливаем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host

      # 4. Логинимся в GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Устанавливаем переменные
      - name: Set variables
        id: vars
        run: |
          echo "BUILDTIME=$(date)" >> $GITHUB_ENV

      # 7. Сборка и пуш AMD64_v1
      - name: Build and push mihomo AMD64_v1
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            TAG=${{ env.VERSION }}
            BUILDTIME=${{ env.BUILDTIME }}
            AMD64VERSION=v1
          tags: |
            ghcr.io/medium1992/mihomo-proxy-ros:alpha-amd64v1
            medium1992/mihomo-proxy-ros:alpha-amd64v1

      # 8. Сборка и пуш AMD64_v2
      - name: Build and push mihomo AMD64_v2
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            TAG=${{ env.VERSION }}
            BUILDTIME=${{ env.BUILDTIME }}
            AMD64VERSION=v2
          tags: |
            ghcr.io/medium1992/mihomo-proxy-ros:alpha-amd64v2
            medium1992/mihomo-proxy-ros:alpha-amd64v2

      # 9. Сборка и пуш multi-arch (AMD64_v3) + latest
      - name: Build and push mihomo multi-arch
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            TAG=${{ env.VERSION }}
            BUILDTIME=${{ env.BUILDTIME }}
            AMD64VERSION=v3
          tags: |
            ghcr.io/medium1992/mihomo-proxy-ros:alpha
            medium1992/mihomo-proxy-ros:alpha
